url= https://tta-bank-digital-973242068062.us-west1.run.app/
name=Raju
email=syue123@yopmail.com
pwd=12345
H1= Dashboard
browser=chrome
fwdtext=The OrangeHRM system is not configured to receive email notifications. Please contact your OrangeHRM administrator to reset your password

iframe email =xadala6620@desiys.com

orange_url = https://awesomeqa.com/hr/web/index.php/auth/login
ohr_username=admin
ohr_password=Hacker@4321
ohr_expected_username=PIM

wohr_username=admins
wohr_password=Hacker@4321123
invalidmsg =Invalid credentials

employeename= t
username= Surya66
addpwd=Surya@27
addedname= Johnathon Bahringer

fname=Surya
mname=N
lname=king
empid=006
otherid=12345
dlicence=8989
licence=2026-12-12
dob=1997-12-12

Street1=2939
Street2=7th cross
city=Mandya
State=Karnataka
zipcode=571401
homenum=9878156178
mobile=7876145671
work=QA
webmail=acc@yopmail.com
oemail=bcd@yopmail.com

//emergencycontctdetails
ename=Raj
relationship=friend
telephone= 9891897891
emobile=6787656787
worktelephone=9898156718


